### ISSUE TITLE
Pose estimation for localization doesn't take on first click

### ISSUE THREAD

**Issue by maxsvetlik** [ut-amrl/robofleet_webviz#9]
Giving a robot an estimated pose for localization in robofleet requires doing `Localization > Pose > Click + Drag` two times before the pose estimation is actually communicated to the robot.

**Comment by kvsikand** [comment]
Have determined that this is a bug with the robofleet_client

Esseentially, calling `advertise` and then immediately `publish`ing to a new topic causes the message to get dropped. A dumb fix here is to add a short `sleep` right after line 68 in https://github.com/ut-amrl/robofleet_client/blob/master/src/RosClientNode.hpp

@loganzartman I think this may be due to the use of the `AsyncSpinner` for this ROS node. Was there a particular reason for using that as opposed to the standard ROS setup? Or, is there another, cleaner fix you can think of?

**Comment by kvsikand** [comment]
Oh, I see why we didn't use the standard spin, because we need to set up the websocket connection after. Well, another thing that fixed this was giving the AsyncSpinner 2 threads (at the top of that file), rather than adding a sleep. I think this causes the `advertise` to immediately do all its ROS magic, so by the time the publish happens, we are good to go. Does this fix sound good?

**Comment by loganzartman** [comment]
yep, you can give AsyncSpinner as many threads as you want. I don't really understand why this happens without debugging it, but I guess it could have to do with the things we do to drop messages to avoid backpressure? This is actually interesting--if you ever actually use "direct mode" in the robot client, giving the ROS spinner more threads might make it perform better.

**Comment by loganzartman** [comment]
+1 for avoiding any and all usages of `sleep` :)

**Comment by maxsvetlik** [comment]
I'll just note that this issue happens when setting a navigation goal in robofleet as well. Likely the same issue for setting pose and a nav goal.

**Comment by kvsikand** [comment]
Yeah @maxsvetlik  I was able to repro this in both message types.

@loganzartman  yeah it was a wild error, and even increasing the queue size on the advertiser didn't help. Going to go ahead with the multi-thread method (the jackal's computer has more than one execution thread, right @maxsvetlik ?)
